services:
  app:
    build:
      context: .
    image: advertiser_man
    container_name: advertiser_man
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    # user: "www-data:www-data"